name: modid-db-sylv
description: Searches Modrinth and other places for mod IDs and adds them to the mod ID database. This can be used to check if a mod ID has already been taken by another mod.
author: SylvKT <18603248+SylvKT@users.noreply.github.com>
inputs:
  error:
    description: 'The error message to display, if any'
    required: false
    default: ''
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: 'ghcr.io/SylvKT/modid-db-sylv:v1'
  args:
    - ${{ inputs.error }}
